version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5000:80" # Mapeia a porta 80 da API .NET para a porta 5000 do host

  angular:
    build:
      context: .
      dockerfile: Dockerfile-angular
    ports:
      - "4200:4200" # Mapeia a porta 4200 do Angular para a porta 4200 do host
